apiVersion: v1
kind: Pod
metadata:
  name: gpu-scheduler-check
  labels:
    app: gpu-scheduler-check
spec:
  containers:
  - name: gpu-check
    image: bash
    command: ["bash"]
    args:
    - -c
    - |
      while true; do
        echo "Node Name: $NODE_NAME"
        echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
        echo "---"
        sleep 5
      done
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  restartPolicy: Always
