apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gpu-scheduler-check
  labels:
    app: gpu-scheduler-check
spec:
  serviceName: gpu-scheduler-check
  replicas: 5
  selector:
    matchLabels:
      app: gpu-scheduler-check
  template:
    metadata:
      labels:
        app: gpu-scheduler-check
      annotations:
        gpu-scheduling-map: |
          0=node1:0,1
          1=node2:2
          2=node3:0,1,2
          3=node4:3
          4=node4:3
    spec:
      schedulerName: gpu-scheduler
      containers:
      - name: gpu-check
        image: bash
        command: ["bash"]
        args:
        - -c
        - |
          while true; do
            echo "Node Name: $NODE_NAME"
            echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
            echo "---"
            sleep 5
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always
