[project]
name = "gpu-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "kubernetes>=33.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
